
all:test pekere layout string array

test:test.c
	gcc -std=gnu11 test.c -o test

pekere:pekere.c
	gcc -std=gnu11 pekere.c -o pekere

layout:layout.c
	gcc -std=gnu11 layout.c -o layout

string:string.c
	gcc -std=gnu11 string.c -o string

array:array.c
	gcc -std=gnu11 array.c -o array

clean:
	rm -f test pekere layout string array
